server:
  port: 9120
spring:
  profiles:
    active: dev
  application:
    name: net-opt-r-datagather-pm-bgbs
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

swagger:
  title: "PM性能-数据汇聚"
  description: "PM 无线侧性能数据汇聚"
  version: "1.0.0"
  contact-name: "ReTiNA"
  contact-url: "www.asiainfo.com"
  contact-email: "retina@asiainfo.com"
  ignore-paths:

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: false
    default-fetch-size: 1000
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/master/*.xml

logging:
  path: /data/log/datagather/